### ISSUE TITLE
Equivalent for the range sensor layer

### ISSUE THREAD

**Issue by doisyg** [DLu/decaying_obstacle_layer#1]
Hello,
I am looking to have the same functionality (decaying) for the range sensor layer.
Was it developed already, and if not, any pointer to where to start? I am planning to use this package as a base.

**Comment by DLu** [comment]
Sorry, I'm not quite sure what you're asking. Can you open a question on answers.ros.org instead?

**Comment by doisyg** [comment]
Hello David,
Sorry if i was not clear. This decaying_obstacle_layer is very useful and as I understand it is a drop in replacement for the obstacle layer in order to have an obstacle decaying feature. Though it is only compatible with pointcloud sensors. I am looking for the same fonctionality for Range sensor (sonar to be precise), and so a layer which will be the equivalent to the pair obstacle_layer/decaying_obstacle_layer for the range_sensor_layer that you also wrote http://wiki.ros.org/range_sensor_layer.
If it does not exists, I see several options:

- A new package
- A pull request with a second dedicated layer for range sensor decaying to this package

If you don't think this topic belongs here, I will open a question on answers.ros.org

**Comment by DLu** [comment]
What's tricky is that the math is more complex for the range_sensor_layer. The decaying_obstacle_layer keeps track of the single cell where lethal obstacles are detected, and sets them to no information after the decay finishes (if nothing else has marked it as an obstacle since). The range_sensor_layer doesn't mark a single cell, but changes the probability of an obstacle for a collection of cells, so removing that probability after a set amount of time doesn't make as much sense to me.

**Comment by doisyg** [comment]
Ok, thanks for your answer, I will then think about an alternative, but I need a way of clearing (dynamic) obstacles marked by an ultrasonic sensor for them not to stay marked indefinitely.

**Comment by DLu** [comment]
I'm not sure exactly how you would model it, but I would make something that decreases the probability of each square of the range_sensor_layer by some amount. But that would be more appropriate in the range_sensor_layer repo, not here, so I'm closing this ticket. Feel free to open a PR or issue on the other repo. Thanks!
